categories:
  - title: "🚀 New Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🧰 Maintenance"
    label: "chore"
exclude-labels:
  - "dependencies"
  - "no-release-notes"
template: |
  ## ✨ Changes
  $CHANGES
change-template: "- $TITLE (#$NUMBER)"
branches:
  - main
