json.extract! user,
              :id,
              :username,
              :ugent_id,
              :first_name,
              :last_name,
              :email,
              :permission,
              :time_zone,
              :lang
