name: Capybara

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6
      env:
        RAILS_ENV: "test"
        DATABASE_URL: "mysql2://root:dodona@mysql:3306/dodona_test"
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: "dodona_test"
          MYSQL_ROOT_PASSWORD: "dodona"
          MYSQL_HOST: "localhost"
    steps:
    - uses: actions/checkout@v1
    - name: Install node and yarn
      run: |
        apt-get update
        apt-get -y install --no-install-recommends apt-transport-https
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
        curl -sL https://deb.nodesource.com/setup_12.x | bash -
        apt-get update
        apt-get -y --no-install-recommends install nodejs yarn
    - name: Install Chrome
      run: |
        apt-get update
        apt-get install -yq libgconf-2-4
        apt-get install -y wget xvfb --no-install-recommends
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        apt-get update
        apt-get install -y google-chrome-stable --no-install-recommends
        rm -rf /var/lib/apt/lists/*
    - name: Install sudo dependency
      run: |
        apt-get update
        apt-get install -yq sudo
    - name: Setup chromium-chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: Cache Ruby dependencies
      uses: actions/cache@v1
      with:
        path: /usr/local/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Get the Yarn cache directory
      id: yarn-cache
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache Yarn dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-fix-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-fix-
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: /__w/dodona/dodona/node_modules
        key: ${{ runner.os }}-node_modules-fix-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-node_modules-fix-
    - name: Install dependencies
      run: |
        gem install bundler:2.0.2
        bundle config path
        bundle install --jobs 4 --retry 3
        yarn install
    - name: Show installed chrome version
      run: |
        google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1
    - name: Run tests
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        git config --global user.email "dodona@ugent.be"
        git config --global user.name "Dodona"
        bundle exec rails test:system
