name: Deploy Naos

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

concurrency: 
  group: deploy-naos
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && github.event.label.name == 'deploy naos') }}
    environment: 
      name: naos
      url: https://naos.ugent.be
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MESTRA_KEY }}
        known_hosts: ${{ secrets.MESTRA_HOST }}
    - name: Run deploy
      run: |
        echo "deploy naos $GITHUB_SHA" | ssh -p 4840 dodona@mestra.ugent.be
    - name: Remove deploy label
      if: github.event.action == 'labeled'
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: deploy naos
        type: remove
